# Generated by Django 5.0.7 on 2024-07-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='platFormId',
            new_name='platformId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
