# Generated by Django 5.0.7 on 2024-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
