# Generated by Django 5.0.7 on 2024-07-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='photo',
            new_name='url',
        ),
    ]
