# Generated by Django 5.0.7 on 2024-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_rename_photo_pet_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='pet_photos')),
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='user_id',
            new_name='user',
        ),
    ]
