# Generated by Django 5.0.7 on 2024-07-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_image_remove_diary_imgfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='user',
        ),
    ]
