# Generated by Django 5.0.7 on 2024-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_alter_diary_pet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='diary',
            name='pet_id',
            field=models.PositiveIntegerField(),
        ),
    ]
