# Generated by Django 5.0.7 on 2024-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('imgUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
