# Generated by Django 5.0.7 on 2024-07-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('funeral', 'funeral'), ('hospice', 'hospice')], max_length=30),
        ),
    ]
